/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddOrganizationUsersResponse
 */
export interface AddOrganizationUsersResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof AddOrganizationUsersResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof AddOrganizationUsersResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AddOrganizationUsersResponse
     */
    usersAdded?: Array<string>;
}

/**
 * Check if a given object implements the AddOrganizationUsersResponse interface.
 */
export function instanceOfAddOrganizationUsersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddOrganizationUsersResponseFromJSON(json: any): AddOrganizationUsersResponse {
    return AddOrganizationUsersResponseFromJSONTyped(json, false);
}

export function AddOrganizationUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationUsersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'usersAdded': !exists(json, 'users_added') ? undefined : json['users_added'],
    };
}

export function AddOrganizationUsersResponseToJSON(value?: AddOrganizationUsersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'users_added': value.usersAdded,
    };
}

