/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AddOrganizationUsersRequestUsersInner } from './AddOrganizationUsersRequestUsersInner';
import {
    AddOrganizationUsersRequestUsersInnerFromJSON,
    AddOrganizationUsersRequestUsersInnerFromJSONTyped,
    AddOrganizationUsersRequestUsersInnerToJSON,
} from './AddOrganizationUsersRequestUsersInner';

/**
 * 
 * @export
 * @interface AddOrganizationUsersRequest
 */
export interface AddOrganizationUsersRequest {
    /**
     * Users to be added to the organization.
     * @type {Array<AddOrganizationUsersRequestUsersInner>}
     * @memberof AddOrganizationUsersRequest
     */
    users?: Array<AddOrganizationUsersRequestUsersInner>;
}

/**
 * Check if a given object implements the AddOrganizationUsersRequest interface.
 */
export function instanceOfAddOrganizationUsersRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddOrganizationUsersRequestFromJSON(json: any): AddOrganizationUsersRequest {
    return AddOrganizationUsersRequestFromJSONTyped(json, false);
}

export function AddOrganizationUsersRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddOrganizationUsersRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'users': !exists(json, 'users') ? undefined : ((json['users'] as Array<any>).map(AddOrganizationUsersRequestUsersInnerFromJSON)),
    };
}

export function AddOrganizationUsersRequestToJSON(value?: AddOrganizationUsersRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'users': value.users === undefined ? undefined : ((value.users as Array<any>).map(AddOrganizationUsersRequestUsersInnerToJSON)),
    };
}

