/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { ApiApplicationsInner } from './ApiApplicationsInner.js';
import {
    ApiApplicationsInnerFromJSON,
    ApiApplicationsInnerFromJSONTyped,
    ApiApplicationsInnerToJSON,
} from './ApiApplicationsInner.js';

/**
 * 
 * @export
 * @interface Api
 */
export interface Api {
    /**
     * The API's unique identifier.
     * @type {string}
     * @memberof Api
     */
    id?: string;
    /**
     * Response code.
     * @type {string}
     * @memberof Api
     */
    code?: string;
    /**
     * The API's name.
     * @type {string}
     * @memberof Api
     */
    name?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof Api
     */
    message?: string;
    /**
     * The API's audience.
     * @type {string}
     * @memberof Api
     */
    audience?: string;
    /**
     * 
     * @type {Array<ApiApplicationsInner>}
     * @memberof Api
     */
    applications?: Array<ApiApplicationsInner>;
}

/**
 * Check if a given object implements the Api interface.
 */
export function instanceOfApi(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiFromJSON(json: any): Api {
    return ApiFromJSONTyped(json, false);
}

export function ApiFromJSONTyped(json: any, ignoreDiscriminator: boolean): Api {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'audience': !exists(json, 'audience') ? undefined : json['audience'],
        'applications': !exists(json, 'applications') ? undefined : ((json['applications'] as Array<any>).map(ApiApplicationsInnerFromJSON)),
    };
}

export function ApiToJSON(value?: Api | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'code': value.code,
        'name': value.name,
        'message': value.message,
        'audience': value.audience,
        'applications': value.applications === undefined ? undefined : ((value.applications as Array<any>).map(ApiApplicationsInnerToJSON)),
    };
}

