/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApplicationsInner
 */
export interface ApiApplicationsInner {
    /**
     * 
     * @type {string}
     * @memberof ApiApplicationsInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiApplicationsInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiApplicationsInner
     */
    type?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ApiApplicationsInner
     */
    isActive?: boolean;
}

/**
 * Check if a given object implements the ApiApplicationsInner interface.
 */
export function instanceOfApiApplicationsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApplicationsInnerFromJSON(json: any): ApiApplicationsInner {
    return ApiApplicationsInnerFromJSONTyped(json, false);
}

export function ApiApplicationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApplicationsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'isActive': !exists(json, 'is_active') ? undefined : json['is_active'],
    };
}

export function ApiApplicationsInnerToJSON(value?: ApiApplicationsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'is_active': value.isActive,
    };
}

