/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CreateUserRequestIdentitiesInnerDetails } from './CreateUserRequestIdentitiesInnerDetails';
import {
    CreateUserRequestIdentitiesInnerDetailsFromJSON,
    CreateUserRequestIdentitiesInnerDetailsFromJSONTyped,
    CreateUserRequestIdentitiesInnerDetailsToJSON,
} from './CreateUserRequestIdentitiesInnerDetails';

/**
 * The result of the user creation operation.
 * @export
 * @interface CreateUserRequestIdentitiesInner
 */
export interface CreateUserRequestIdentitiesInner {
    /**
     * The type of identity to create, for e.g. email.
     * @type {string}
     * @memberof CreateUserRequestIdentitiesInner
     */
    type?: CreateUserRequestIdentitiesInnerTypeEnum;
    /**
     * 
     * @type {CreateUserRequestIdentitiesInnerDetails}
     * @memberof CreateUserRequestIdentitiesInner
     */
    details?: CreateUserRequestIdentitiesInnerDetails;
}


/**
 * @export
 */
export const CreateUserRequestIdentitiesInnerTypeEnum = {
    Email: 'email'
} as const;
export type CreateUserRequestIdentitiesInnerTypeEnum = typeof CreateUserRequestIdentitiesInnerTypeEnum[keyof typeof CreateUserRequestIdentitiesInnerTypeEnum];


/**
 * Check if a given object implements the CreateUserRequestIdentitiesInner interface.
 */
export function instanceOfCreateUserRequestIdentitiesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUserRequestIdentitiesInnerFromJSON(json: any): CreateUserRequestIdentitiesInner {
    return CreateUserRequestIdentitiesInnerFromJSONTyped(json, false);
}

export function CreateUserRequestIdentitiesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequestIdentitiesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'details': !exists(json, 'details') ? undefined : CreateUserRequestIdentitiesInnerDetailsFromJSON(json['details']),
    };
}

export function CreateUserRequestIdentitiesInnerToJSON(value?: CreateUserRequestIdentitiesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'details': CreateUserRequestIdentitiesInnerDetailsToJSON(value.details),
    };
}

