/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationRequest
 */
export interface CreateOrganizationRequest {
    /**
     * The organization's name.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    name?: string;
    /**
     * The organization's feature flag settings.
     * @type {{ [key: string]: string; }}
     * @memberof CreateOrganizationRequest
     */
    featureFlags?: { [key: string]: string; };
    /**
     * The organization's ID.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    externalId?: string;
    /**
     * The organization's brand settings - background color.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    backgroundColor?: string;
    /**
     * The organization's brand settings - button color.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    buttonColor?: string;
    /**
     * The organization's brand settings - button text color.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    buttonTextColor?: string;
    /**
     * The organization's brand settings - link color.
     * @type {string}
     * @memberof CreateOrganizationRequest
     */
    linkColor?: string;
}


/**
 * @export
 */
export const CreateOrganizationRequestFeatureFlagsEnum = {
    Str: 'str',
    Int: 'int',
    Bool: 'bool'
} as const;
export type CreateOrganizationRequestFeatureFlagsEnum = typeof CreateOrganizationRequestFeatureFlagsEnum[keyof typeof CreateOrganizationRequestFeatureFlagsEnum];


/**
 * Check if a given object implements the CreateOrganizationRequest interface.
 */
export function instanceOfCreateOrganizationRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateOrganizationRequestFromJSON(json: any): CreateOrganizationRequest {
    return CreateOrganizationRequestFromJSONTyped(json, false);
}

export function CreateOrganizationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'featureFlags': !exists(json, 'feature_flags') ? undefined : json['feature_flags'],
        'externalId': !exists(json, 'external_id') ? undefined : json['external_id'],
        'backgroundColor': !exists(json, 'background_color') ? undefined : json['background_color'],
        'buttonColor': !exists(json, 'button_color') ? undefined : json['button_color'],
        'buttonTextColor': !exists(json, 'button_text_color') ? undefined : json['button_text_color'],
        'linkColor': !exists(json, 'link_color') ? undefined : json['link_color'],
    };
}

export function CreateOrganizationRequestToJSON(value?: CreateOrganizationRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'feature_flags': value.featureFlags,
        'external_id': value.externalId,
        'background_color': value.backgroundColor,
        'button_color': value.buttonColor,
        'button_text_color': value.buttonTextColor,
        'link_color': value.linkColor,
    };
}

