/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { CreateApplicationResponseApplication } from './CreateApplicationResponseApplication.js';
import {
    CreateApplicationResponseApplicationFromJSON,
    CreateApplicationResponseApplicationFromJSONTyped,
    CreateApplicationResponseApplicationToJSON,
} from './CreateApplicationResponseApplication.js';

/**
 * 
 * @export
 * @interface CreateApplicationResponse
 */
export interface CreateApplicationResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof CreateApplicationResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof CreateApplicationResponse
     */
    message?: string;
    /**
     * 
     * @type {CreateApplicationResponseApplication}
     * @memberof CreateApplicationResponse
     */
    application?: CreateApplicationResponseApplication;
}

/**
 * Check if a given object implements the CreateApplicationResponse interface.
 */
export function instanceOfCreateApplicationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateApplicationResponseFromJSON(json: any): CreateApplicationResponse {
    return CreateApplicationResponseFromJSONTyped(json, false);
}

export function CreateApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApplicationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'application': !exists(json, 'application') ? undefined : CreateApplicationResponseApplicationFromJSON(json['application']),
    };
}

export function CreateApplicationResponseToJSON(value?: CreateApplicationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'application': CreateApplicationResponseApplicationToJSON(value.application),
    };
}

