/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateFeatureFlagRequest
 */
export interface CreateFeatureFlagRequest {
    /**
     * The name of the flag.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    name: string;
    /**
     * Description of the flag purpose.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    description?: string;
    /**
     * The flag identifier to use in code.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    key: string;
    /**
     * The variable type.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    type: CreateFeatureFlagRequestTypeEnum;
    /**
     * Allow the flag to be overridden at a different level.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    allowOverrideLevel?: CreateFeatureFlagRequestAllowOverrideLevelEnum;
    /**
     * Default value for the flag used by environments and organizations.
     * @type {string}
     * @memberof CreateFeatureFlagRequest
     */
    defaultValue: string;
}


/**
 * @export
 */
export const CreateFeatureFlagRequestTypeEnum = {
    Str: 'str',
    Int: 'int',
    Bool: 'bool'
} as const;
export type CreateFeatureFlagRequestTypeEnum = typeof CreateFeatureFlagRequestTypeEnum[keyof typeof CreateFeatureFlagRequestTypeEnum];

/**
 * @export
 */
export const CreateFeatureFlagRequestAllowOverrideLevelEnum = {
    Env: 'env',
    Org: 'org'
} as const;
export type CreateFeatureFlagRequestAllowOverrideLevelEnum = typeof CreateFeatureFlagRequestAllowOverrideLevelEnum[keyof typeof CreateFeatureFlagRequestAllowOverrideLevelEnum];


/**
 * Check if a given object implements the CreateFeatureFlagRequest interface.
 */
export function instanceOfCreateFeatureFlagRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "defaultValue" in value;

    return isInstance;
}

export function CreateFeatureFlagRequestFromJSON(json: any): CreateFeatureFlagRequest {
    return CreateFeatureFlagRequestFromJSONTyped(json, false);
}

export function CreateFeatureFlagRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateFeatureFlagRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'key': json['key'],
        'type': json['type'],
        'allowOverrideLevel': !exists(json, 'allow_override_level') ? undefined : json['allow_override_level'],
        'defaultValue': json['default_value'],
    };
}

export function CreateFeatureFlagRequestToJSON(value?: CreateFeatureFlagRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'key': value.key,
        'type': value.type,
        'allow_override_level': value.allowOverrideLevel,
        'default_value': value.defaultValue,
    };
}

