/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateOrganizationUserRoleRequest
 */
export interface CreateOrganizationUserRoleRequest {
    /**
     * The role id.
     * @type {string}
     * @memberof CreateOrganizationUserRoleRequest
     */
    roleId?: string;
}

/**
 * Check if a given object implements the CreateOrganizationUserRoleRequest interface.
 */
export function instanceOfCreateOrganizationUserRoleRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateOrganizationUserRoleRequestFromJSON(json: any): CreateOrganizationUserRoleRequest {
    return CreateOrganizationUserRoleRequestFromJSONTyped(json, false);
}

export function CreateOrganizationUserRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationUserRoleRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roleId': !exists(json, 'role_id') ? undefined : json['role_id'],
    };
}

export function CreateOrganizationUserRoleRequestToJSON(value?: CreateOrganizationUserRoleRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role_id': value.roleId,
    };
}

