/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateSubscriberSuccessResponseSubscriber
 */
export interface CreateSubscriberSuccessResponseSubscriber {
    /**
     * A unique identifier for the subscriber.
     * @type {string}
     * @memberof CreateSubscriberSuccessResponseSubscriber
     */
    subscriberId?: string;
}

/**
 * Check if a given object implements the CreateSubscriberSuccessResponseSubscriber interface.
 */
export function instanceOfCreateSubscriberSuccessResponseSubscriber(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateSubscriberSuccessResponseSubscriberFromJSON(json: any): CreateSubscriberSuccessResponseSubscriber {
    return CreateSubscriberSuccessResponseSubscriberFromJSONTyped(json, false);
}

export function CreateSubscriberSuccessResponseSubscriberFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriberSuccessResponseSubscriber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subscriberId': !exists(json, 'subscriber_id') ? undefined : json['subscriber_id'],
    };
}

export function CreateSubscriberSuccessResponseSubscriberToJSON(value?: CreateSubscriberSuccessResponseSubscriber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subscriber_id': value.subscriberId,
    };
}

