/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CreateOrganizationResponseOrganization
 */
export interface CreateOrganizationResponseOrganization {
    /**
     * The organization's code.
     * @type {string}
     * @memberof CreateOrganizationResponseOrganization
     */
    code?: string;
}

/**
 * Check if a given object implements the CreateOrganizationResponseOrganization interface.
 */
export function instanceOfCreateOrganizationResponseOrganization(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateOrganizationResponseOrganizationFromJSON(json: any): CreateOrganizationResponseOrganization {
    return CreateOrganizationResponseOrganizationFromJSONTyped(json, false);
}

export function CreateOrganizationResponseOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationResponseOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function CreateOrganizationResponseOrganizationToJSON(value?: CreateOrganizationResponseOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

