/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Additional details required to create the user.
 * @export
 * @interface CreateUserRequestIdentitiesInnerDetails
 */
export interface CreateUserRequestIdentitiesInnerDetails {
    /**
     * The email address of the user.
     * @type {string}
     * @memberof CreateUserRequestIdentitiesInnerDetails
     */
    email?: string;
}

/**
 * Check if a given object implements the CreateUserRequestIdentitiesInnerDetails interface.
 */
export function instanceOfCreateUserRequestIdentitiesInnerDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateUserRequestIdentitiesInnerDetailsFromJSON(json: any): CreateUserRequestIdentitiesInnerDetails {
    return CreateUserRequestIdentitiesInnerDetailsFromJSONTyped(json, false);
}

export function CreateUserRequestIdentitiesInnerDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserRequestIdentitiesInnerDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function CreateUserRequestIdentitiesInnerDetailsToJSON(value?: CreateUserRequestIdentitiesInnerDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

