/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { GetApplicationResponseApplication } from './GetApplicationResponseApplication.js';
import {
    GetApplicationResponseApplicationFromJSON,
    GetApplicationResponseApplicationFromJSONTyped,
    GetApplicationResponseApplicationToJSON,
} from './GetApplicationResponseApplication.js';

/**
 * 
 * @export
 * @interface GetApplicationResponse
 */
export interface GetApplicationResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetApplicationResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetApplicationResponse
     */
    message?: string;
    /**
     * 
     * @type {GetApplicationResponseApplication}
     * @memberof GetApplicationResponse
     */
    application?: GetApplicationResponseApplication;
}

/**
 * Check if a given object implements the GetApplicationResponse interface.
 */
export function instanceOfGetApplicationResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetApplicationResponseFromJSON(json: any): GetApplicationResponse {
    return GetApplicationResponseFromJSONTyped(json, false);
}

export function GetApplicationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApplicationResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'application': !exists(json, 'application') ? undefined : GetApplicationResponseApplicationFromJSON(json['application']),
    };
}

export function GetApplicationResponseToJSON(value?: GetApplicationResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'application': GetApplicationResponseApplicationToJSON(value.application),
    };
}

