/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface GetApplicationResponseApplication
 */
export interface GetApplicationResponseApplication {
    /**
     * The application's identifier.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    id?: string;
    /**
     * The application's name.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    name?: string;
    /**
     * The application's type.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    type?: string;
    /**
     * The application's client id.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    clientId?: string;
    /**
     * The application's client secret.
     * @type {string}
     * @memberof GetApplicationResponseApplication
     */
    clientSecret?: string;
}

/**
 * Check if a given object implements the GetApplicationResponseApplication interface.
 */
export function instanceOfGetApplicationResponseApplication(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetApplicationResponseApplicationFromJSON(json: any): GetApplicationResponseApplication {
    return GetApplicationResponseApplicationFromJSONTyped(json, false);
}

export function GetApplicationResponseApplicationFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetApplicationResponseApplication {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'clientSecret': !exists(json, 'client_secret') ? undefined : json['client_secret'],
    };
}

export function GetApplicationResponseApplicationToJSON(value?: GetApplicationResponseApplication | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
        'client_id': value.clientId,
        'client_secret': value.clientSecret,
    };
}

