/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { GetOrganizationFeatureFlagsResponseFeatureFlagsValue } from './GetOrganizationFeatureFlagsResponseFeatureFlagsValue.js';
import {
    GetOrganizationFeatureFlagsResponseFeatureFlagsValueFromJSON,
    GetOrganizationFeatureFlagsResponseFeatureFlagsValueFromJSONTyped,
    GetOrganizationFeatureFlagsResponseFeatureFlagsValueToJSON,
} from './GetOrganizationFeatureFlagsResponseFeatureFlagsValue.js';

/**
 * 
 * @export
 * @interface GetEnvironmentFeatureFlagsResponse
 */
export interface GetEnvironmentFeatureFlagsResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetEnvironmentFeatureFlagsResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetEnvironmentFeatureFlagsResponse
     */
    message?: string;
    /**
     * The environment's feature flag settings.
     * @type {{ [key: string]: GetOrganizationFeatureFlagsResponseFeatureFlagsValue; }}
     * @memberof GetEnvironmentFeatureFlagsResponse
     */
    featureFlags?: { [key: string]: GetOrganizationFeatureFlagsResponseFeatureFlagsValue; };
    /**
     * Pagination token.
     * @type {string}
     * @memberof GetEnvironmentFeatureFlagsResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetEnvironmentFeatureFlagsResponse interface.
 */
export function instanceOfGetEnvironmentFeatureFlagsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetEnvironmentFeatureFlagsResponseFromJSON(json: any): GetEnvironmentFeatureFlagsResponse {
    return GetEnvironmentFeatureFlagsResponseFromJSONTyped(json, false);
}

export function GetEnvironmentFeatureFlagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEnvironmentFeatureFlagsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'featureFlags': !exists(json, 'feature_flags') ? undefined : (mapValues(json['feature_flags'], GetOrganizationFeatureFlagsResponseFeatureFlagsValueFromJSON)),
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
    };
}

export function GetEnvironmentFeatureFlagsResponseToJSON(value?: GetEnvironmentFeatureFlagsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'feature_flags': value.featureFlags === undefined ? undefined : (mapValues(value.featureFlags, GetOrganizationFeatureFlagsResponseFeatureFlagsValueToJSON)),
        'next_token': value.nextToken,
    };
}

