/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { Permissions } from './Permissions.js';
import {
    PermissionsFromJSON,
    PermissionsFromJSONTyped,
    PermissionsToJSON,
} from './Permissions.js';

/**
 * 
 * @export
 * @interface GetPermissionsResponse
 */
export interface GetPermissionsResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetPermissionsResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetPermissionsResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Permissions>}
     * @memberof GetPermissionsResponse
     */
    permissions?: Array<Permissions>;
    /**
     * Pagination token.
     * @type {string}
     * @memberof GetPermissionsResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetPermissionsResponse interface.
 */
export function instanceOfGetPermissionsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPermissionsResponseFromJSON(json: any): GetPermissionsResponse {
    return GetPermissionsResponseFromJSONTyped(json, false);
}

export function GetPermissionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPermissionsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'permissions': !exists(json, 'permissions') ? undefined : ((json['permissions'] as Array<any>).map(PermissionsFromJSON)),
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
    };
}

export function GetPermissionsResponseToJSON(value?: GetPermissionsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'permissions': value.permissions === undefined ? undefined : ((value.permissions as Array<any>).map(PermissionsToJSON)),
        'next_token': value.nextToken,
    };
}

