/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { SubscribersSubscriber } from './SubscribersSubscriber.js';
import {
    SubscribersSubscriberFromJSON,
    SubscribersSubscriberFromJSONTyped,
    SubscribersSubscriberToJSON,
} from './SubscribersSubscriber.js';

/**
 * 
 * @export
 * @interface GetSubscribersResponse
 */
export interface GetSubscribersResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<SubscribersSubscriber>}
     * @memberof GetSubscribersResponse
     */
    subscribers?: Array<SubscribersSubscriber>;
    /**
     * Pagination token.
     * @type {string}
     * @memberof GetSubscribersResponse
     */
    nextToken?: string;
}

/**
 * Check if a given object implements the GetSubscribersResponse interface.
 */
export function instanceOfGetSubscribersResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSubscribersResponseFromJSON(json: any): GetSubscribersResponse {
    return GetSubscribersResponseFromJSONTyped(json, false);
}

export function GetSubscribersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscribersResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'subscribers': !exists(json, 'subscribers') ? undefined : ((json['subscribers'] as Array<any>).map(SubscribersSubscriberFromJSON)),
        'nextToken': !exists(json, 'next_token') ? undefined : json['next_token'],
    };
}

export function GetSubscribersResponseToJSON(value?: GetSubscribersResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'subscribers': value.subscribers === undefined ? undefined : ((value.subscribers as Array<any>).map(SubscribersSubscriberToJSON)),
        'next_token': value.nextToken,
    };
}

