/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
import type { Subscriber } from './Subscriber.js';
import {
    SubscriberFromJSON,
    SubscriberFromJSONTyped,
    SubscriberToJSON,
} from './Subscriber.js';

/**
 * 
 * @export
 * @interface GetSubscriberResponse
 */
export interface GetSubscriberResponse {
    /**
     * Response code.
     * @type {string}
     * @memberof GetSubscriberResponse
     */
    code?: string;
    /**
     * Response message.
     * @type {string}
     * @memberof GetSubscriberResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<Subscriber>}
     * @memberof GetSubscriberResponse
     */
    subscribers?: Array<Subscriber>;
}

/**
 * Check if a given object implements the GetSubscriberResponse interface.
 */
export function instanceOfGetSubscriberResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetSubscriberResponseFromJSON(json: any): GetSubscriberResponse {
    return GetSubscriberResponseFromJSONTyped(json, false);
}

export function GetSubscriberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubscriberResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'subscribers': !exists(json, 'subscribers') ? undefined : ((json['subscribers'] as Array<any>).map(SubscriberFromJSON)),
    };
}

export function GetSubscriberResponseToJSON(value?: GetSubscriberResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'subscribers': value.subscribers === undefined ? undefined : ((value.subscribers as Array<any>).map(SubscriberToJSON)),
    };
}

