/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganizationUserRole
 */
export interface OrganizationUserRole {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRole
     */
    name?: string;
}

/**
 * Check if a given object implements the OrganizationUserRole interface.
 */
export function instanceOfOrganizationUserRole(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationUserRoleFromJSON(json: any): OrganizationUserRole {
    return OrganizationUserRoleFromJSONTyped(json, false);
}

export function OrganizationUserRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserRole {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function OrganizationUserRoleToJSON(value?: OrganizationUserRole | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'key': value.key,
        'name': value.name,
    };
}

