/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationUser
 */
export interface OrganizationUser {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationUser
     */
    firstName?: string;
}

/**
 * Check if a given object implements the OrganizationUser interface.
 */
export function instanceOfOrganizationUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationUserFromJSON(json: any): OrganizationUser {
    return OrganizationUserFromJSONTyped(json, false);
}

export function OrganizationUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
    };
}

export function OrganizationUserToJSON(value?: OrganizationUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'full_name': value.fullName,
        'last_name': value.lastName,
        'first_name': value.firstName,
    };
}

