/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface OrganizationUserRolePermissionsPermissions
 */
export interface OrganizationUserRolePermissionsPermissions {
    /**
     * 
     * @type {string}
     * @memberof OrganizationUserRolePermissionsPermissions
     */
    key?: string;
}

/**
 * Check if a given object implements the OrganizationUserRolePermissionsPermissions interface.
 */
export function instanceOfOrganizationUserRolePermissionsPermissions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrganizationUserRolePermissionsPermissionsFromJSON(json: any): OrganizationUserRolePermissionsPermissions {
    return OrganizationUserRolePermissionsPermissionsFromJSONTyped(json, false);
}

export function OrganizationUserRolePermissionsPermissionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationUserRolePermissionsPermissions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
    };
}

export function OrganizationUserRolePermissionsPermissionsToJSON(value?: OrganizationUserRolePermissionsPermissions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
    };
}

