/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ReplaceRedirectCallbackURLsRequest
 */
export interface ReplaceRedirectCallbackURLsRequest {
    /**
     * Array of callback urls.
     * @type {Array<string>}
     * @memberof ReplaceRedirectCallbackURLsRequest
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the ReplaceRedirectCallbackURLsRequest interface.
 */
export function instanceOfReplaceRedirectCallbackURLsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReplaceRedirectCallbackURLsRequestFromJSON(json: any): ReplaceRedirectCallbackURLsRequest {
    return ReplaceRedirectCallbackURLsRequestFromJSONTyped(json, false);
}

export function ReplaceRedirectCallbackURLsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceRedirectCallbackURLsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'urls': !exists(json, 'urls') ? undefined : json['urls'],
    };
}

export function ReplaceRedirectCallbackURLsRequestToJSON(value?: ReplaceRedirectCallbackURLsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'urls': value.urls,
    };
}

