/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplaceLogoutRedirectURLsRequest
 */
export interface ReplaceLogoutRedirectURLsRequest {
    /**
     * Array of logout urls.
     * @type {Array<string>}
     * @memberof ReplaceLogoutRedirectURLsRequest
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the ReplaceLogoutRedirectURLsRequest interface.
 */
export function instanceOfReplaceLogoutRedirectURLsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReplaceLogoutRedirectURLsRequestFromJSON(json: any): ReplaceLogoutRedirectURLsRequest {
    return ReplaceLogoutRedirectURLsRequestFromJSONTyped(json, false);
}

export function ReplaceLogoutRedirectURLsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplaceLogoutRedirectURLsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'urls': !exists(json, 'urls') ? undefined : json['urls'],
    };
}

export function ReplaceLogoutRedirectURLsRequestToJSON(value?: ReplaceLogoutRedirectURLsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'urls': value.urls,
    };
}

