/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Roles
 */
export interface Roles {
    /**
     * The role identifier to use in code.
     * @type {string}
     * @memberof Roles
     */
    key?: string;
    /**
     * The role's name.
     * @type {string}
     * @memberof Roles
     */
    name?: string;
    /**
     * The role's description.
     * @type {string}
     * @memberof Roles
     */
    description?: string;
}

/**
 * Check if a given object implements the Roles interface.
 */
export function instanceOfRoles(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RolesFromJSON(json: any): Roles {
    return RolesFromJSONTyped(json, false);
}

export function RolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Roles {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': !exists(json, 'key') ? undefined : json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function RolesToJSON(value?: Roles | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'name': value.name,
        'description': value.description,
    };
}

