/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RolesPermissionResponseInner
 */
export interface RolesPermissionResponseInner {
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RolesPermissionResponseInner
     */
    description?: string;
}

/**
 * Check if a given object implements the RolesPermissionResponseInner interface.
 */
export function instanceOfRolesPermissionResponseInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RolesPermissionResponseInnerFromJSON(json: any): RolesPermissionResponseInner {
    return RolesPermissionResponseInnerFromJSONTyped(json, false);
}

export function RolesPermissionResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): RolesPermissionResponseInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'key': !exists(json, 'key') ? undefined : json['key'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function RolesPermissionResponseInnerToJSON(value?: RolesPermissionResponseInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'key': value.key,
        'name': value.name,
        'description': value.description,
    };
}

