/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface Subscriber
 */
export interface Subscriber {
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    preferredEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof Subscriber
     */
    lastName?: string;
}

/**
 * Check if a given object implements the Subscriber interface.
 */
export function instanceOfSubscriber(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriberFromJSON(json: any): Subscriber {
    return SubscriberFromJSONTyped(json, false);
}

export function SubscriberFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscriber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'preferredEmail': !exists(json, 'preferred_email') ? undefined : json['preferred_email'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
    };
}

export function SubscriberToJSON(value?: Subscriber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'preferred_email': value.preferredEmail,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

