/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenIntrospect
 */
export interface TokenIntrospect {
    /**
     * Indicates the status of the token.
     * @type {boolean}
     * @memberof TokenIntrospect
     */
    active?: boolean;
    /**
     * Array of intended token recipients.
     * @type {Array<string>}
     * @memberof TokenIntrospect
     */
    aud?: Array<string>;
    /**
     * Identifier for the requesting client.
     * @type {string}
     * @memberof TokenIntrospect
     */
    clientId?: string;
    /**
     * Token expiration timestamp.
     * @type {string}
     * @memberof TokenIntrospect
     */
    exp?: string;
    /**
     * Token issuance timestamp.
     * @type {string}
     * @memberof TokenIntrospect
     */
    iat?: string;
}

/**
 * Check if a given object implements the TokenIntrospect interface.
 */
export function instanceOfTokenIntrospect(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenIntrospectFromJSON(json: any): TokenIntrospect {
    return TokenIntrospectFromJSONTyped(json, false);
}

export function TokenIntrospectFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenIntrospect {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': !exists(json, 'active') ? undefined : json['active'],
        'aud': !exists(json, 'aud') ? undefined : json['aud'],
        'clientId': !exists(json, 'client_id') ? undefined : json['client_id'],
        'exp': !exists(json, 'exp') ? undefined : json['exp'],
        'iat': !exists(json, 'iat') ? undefined : json['iat'],
    };
}

export function TokenIntrospectToJSON(value?: TokenIntrospect | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'aud': value.aud,
        'client_id': value.clientId,
        'exp': value.exp,
        'iat': value.iat,
    };
}

