/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface UpdateRolesRequest
 */
export interface UpdateRolesRequest {
    /**
     * The role's name.
     * @type {string}
     * @memberof UpdateRolesRequest
     */
    name: string;
    /**
     * The role's description.
     * @type {string}
     * @memberof UpdateRolesRequest
     */
    description?: string;
    /**
     * The role identifier to use in code.
     * @type {string}
     * @memberof UpdateRolesRequest
     */
    key: string;
    /**
     * Set role as default for new users.
     * @type {boolean}
     * @memberof UpdateRolesRequest
     */
    isDefaultRole?: boolean;
}

/**
 * Check if a given object implements the UpdateRolesRequest interface.
 */
export function instanceOfUpdateRolesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function UpdateRolesRequestFromJSON(json: any): UpdateRolesRequest {
    return UpdateRolesRequestFromJSONTyped(json, false);
}

export function UpdateRolesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRolesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'key': json['key'],
        'isDefaultRole': !exists(json, 'is_default_role') ? undefined : json['is_default_role'],
    };
}

export function UpdateRolesRequestToJSON(value?: UpdateRolesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'key': value.key,
        'is_default_role': value.isDefaultRole,
    };
}

