/* tslint:disable */
/* eslint-disable */
/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserIdentityResult } from './UserIdentityResult';
import {
    UserIdentityResultFromJSON,
    UserIdentityResultFromJSONTyped,
    UserIdentityResultToJSON,
} from './UserIdentityResult';

/**
 * 
 * @export
 * @interface UserIdentity
 */
export interface UserIdentity {
    /**
     * The type of identity object created.
     * @type {string}
     * @memberof UserIdentity
     */
    type?: string;
    /**
     * 
     * @type {UserIdentityResult}
     * @memberof UserIdentity
     */
    result?: UserIdentityResult;
}

/**
 * Check if a given object implements the UserIdentity interface.
 */
export function instanceOfUserIdentity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserIdentityFromJSON(json: any): UserIdentity {
    return UserIdentityFromJSONTyped(json, false);
}

export function UserIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIdentity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'result': !exists(json, 'result') ? undefined : UserIdentityResultFromJSON(json['result']),
    };
}

export function UserIdentityToJSON(value?: UserIdentity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'result': UserIdentityResultToJSON(value.result),
    };
}

